#loading nix
. $HOME/.nix-profile/etc/profile.d/nix.sh

osascript -e 'tell application "Terminal" to set current settings of front window to (first settings set whose name is "Homebrew")'
osascript -e 'tell application "Terminal" to set the font size of window 1 to 14'

