#loading nix
. $HOME/.nix-profile/etc/profile.d/nix.sh


# RPROMPT='[%F{yellow}%?%f]'

set -o vi

bindkey '^N' down-line-or-history
bindkey '^P' up-line-or-history

# show which vim mode we are in
setopt PROMPT_SUBST

vim_ins_mode="INS"
vim_cmd_mode="CMD"
vim_mode=$vim_ins_mode

function zle-keymap-select {
  vim_mode="${${KEYMAP/vicmd/${vim_cmd_mode}}/(main|viins)/${vim_ins_mode}}"
  zle reset-prompt
}
zle -N zle-keymap-select

function zle-line-finish {
  vim_mode=$vim_ins_mode
}
zle -N zle-line-finish

PROMPT='%F{green}%n%f %F{magenta}[${vim_mode}]%f %F{blue}%B%~%b%f %# '


unset VIM
unset VIMRUNTIME
