#this file generated by githubTemplates2nix
let tarUrlToDrv = (import /nix/store/y1vinmd8hz5nsqww1rb4a7kqlqy5n1jd-githubTemplate2nix/templatesUtils.nix).tarUrlToDrv;
in
{
    tmp-hs-vscode-hie-cabal = tarUrlToDrv { name = "tmp-hs-vscode-hie-cabal"; url = "https://github.com/countoren/LagdaMdToLagda/archive/8825c96bd9e07bd8c4136a182c5f86cfc008f014.tar.gz"; };
    tmp-basic = tarUrlToDrv { name = "tmp-basic"; url = "https://github.com/countoren/templatesEnv/archive/ad6f47d8ad3e2f02b54660baeedceb7c2075cb7c.tar.gz"; };
    tmp-fs-safe-pages = tarUrlToDrv { name = "tmp-fs-safe-pages"; url = "https://github.com/countoren/WS-EmotionsOfLove/archive/cd6dff91aa9dfba0de8207a111bf2c923e5ced12.tar.gz"; };
    tmp-fs-safe-simple = tarUrlToDrv { name = "tmp-fs-safe-simple"; url = "https://github.com/countoren/WS-EmotionsOfLove/archive/2a34b6e693e7456edca18a4a8c04368dae360454.tar.gz"; };
}
